/**
 * Universal Foundation Set — sub-materi yang harus mastery (Cluster C)
 * terlepas dari distance ke target bab.
 *
 * Generated by scripts/generate-foundation-set.mjs (heuristik dependents +
 * is_maku + is_entry_point), saved di src/data/foundation-set.json.
 *
 * Filosofi: Liping Ma's PUFM — siswa SMP/SMA yang foundation lemah akan
 * terus struggle. Foundation set ini selalu di-cek + threshold lebih ketat.
 */

import foundationData from "@/data/foundation-set.json";

export type FoundationTarget = "sd-low" | "sd-mid" | "sd-high" | "smp" | "sma";

const SETS: Record<FoundationTarget, Set<string>> = {
  "sd-low": new Set<string>(foundationData.sd_low_target.kodes),
  "sd-mid": new Set<string>(foundationData.sd_mid_target.kodes),
  "sd-high": new Set<string>(foundationData.sd_high_target.kodes),
  smp: new Set<string>(foundationData.smp_target.kodes),
  sma: new Set<string>(foundationData.sma_target.kodes),
};

/** Cek apakah kode masuk Universal Foundation Set untuk target tertentu. */
export function isFoundation(kode: string, target: FoundationTarget): boolean {
  return SETS[target].has(kode);
}

/** Daftar kode foundation untuk target. */
export function getFoundationKodes(target: FoundationTarget): string[] {
  return Array.from(SETS[target]);
}

/** Detail lengkap foundation set (untuk admin UI). */
export function getFoundationDetail(target: FoundationTarget) {
  switch (target) {
    case "sd-low": return foundationData.sd_low_target;
    case "sd-mid": return foundationData.sd_mid_target;
    case "sd-high": return foundationData.sd_high_target;
    case "smp": return foundationData.smp_target;
    case "sma": return foundationData.sma_target;
  }
}

/**
 * Pilih foundation target berdasarkan jenjang + kelas user.
 *
 *   SD K1-K2 → sd-low  (pre-numerasi murni)
 *   SD K3-K4 → sd-mid  (number sense + place value)
 *   SD K5-K6 → sd-high (operasi 4 dasar fluency + pecahan)
 *   SMP K7-K9 → smp
 *   SMA K10-K12 → sma
 */
export function pickFoundationTarget(targetJenjang: "SD" | "SMP" | "SMA", targetKelas?: number): FoundationTarget {
  if (targetJenjang === "SMA") return "sma";
  if (targetJenjang === "SMP") return "smp";
  // SD
  const k = targetKelas ?? 6;
  if (k <= 2) return "sd-low";
  if (k <= 4) return "sd-mid";
  return "sd-high";
}

/** Threshold cluster C (foundation) adaptif per jenjang user. */
export const FOUNDATION_THRESHOLD_BY_TARGET: Record<FoundationTarget, number> = {
  "sd-low": foundationData.thresholds?.sd_low ?? 0.75,
  "sd-mid": foundationData.thresholds?.sd_mid ?? 0.80,
  "sd-high": foundationData.thresholds?.sd_high ?? 0.85,
  smp: foundationData.thresholds?.smp ?? 0.90,
  sma: foundationData.thresholds?.sma ?? 0.95,
};

// ============================================================
// Cluster classifier — combine pendekatan A/B/C dengan Foundation Set
// ============================================================

export type Cluster = "A" | "B" | "C";

export type ClusterAssignment = {
  kode: string;
  cluster: Cluster;
  weight: number;
  /** Reason untuk audit. */
  reason: string;
};

/**
 * Classify sub-materi prereq ke Cluster A/B/C.
 *
 * Rules:
 *   1. Kalau kode masuk Universal Foundation Set → Cluster C (terlepas level)
 *   2. Level 1 di pohon prereq (direct prereq) → Cluster A
 *   3. Level 2-3 → Cluster B
 *   4. Level 4+ → Cluster C
 *
 * Weight bertingkat sesuai level + dependents.
 */
export function classifyClusterForPrereq(
  kode: string,
  level: number,
  dependentsCount: number,
  foundationTarget: FoundationTarget,
): ClusterAssignment {
  // Rule 1: Universal Foundation Set always wins
  if (isFoundation(kode, foundationTarget)) {
    return {
      kode,
      cluster: "C",
      weight: 0.15 + Math.min(0.10, dependentsCount * 0.01),
      reason: `Universal Foundation (${foundationTarget}-target)`,
    };
  }

  // Rule 2: direct prereq
  if (level === 1) {
    return {
      kode,
      cluster: "A",
      weight: 0.30 + Math.min(0.15, dependentsCount * 0.02),
      reason: `Direct prereq (level 1, dep=${dependentsCount})`,
    };
  }

  // Rule 3: bridging
  if (level === 2 && dependentsCount >= 10) {
    return {
      kode,
      cluster: "A",
      weight: 0.20,
      reason: `Level 2 high-dep (dep=${dependentsCount}) — fundamental kritis`,
    };
  }
  if (level === 2 || level === 3) {
    return {
      kode,
      cluster: "B",
      weight: 0.20 + Math.min(0.10, dependentsCount * 0.01),
      reason: `Bridging (level ${level}, dep=${dependentsCount})`,
    };
  }

  // Rule 4: deep foundation (kalau bukan di Universal Set)
  return {
    kode,
    cluster: "C",
    weight: Math.max(0.10, 0.18 - (level - 4) * 0.02),
    reason: `Deep foundation (level ${level})`,
  };
}

/** Build cluster assignment untuk seluruh pohon prereq target. */
export function buildClusterAssignmentsForTarget(
  targetKode: string,
  petaNodes: { id: string; level: number }[],
  getDependentsCount: (kode: string) => number,
  targetJenjang: "SD" | "SMP" | "SMA",
  targetKelas?: number,
): ClusterAssignment[] {
  const target = pickFoundationTarget(targetJenjang, targetKelas);
  const result: ClusterAssignment[] = [];
  for (const n of petaNodes) {
    if (n.id === targetKode) continue; // skip target sendiri
    result.push(classifyClusterForPrereq(n.id, n.level, getDependentsCount(n.id), target));
  }
  return normalizeClusterWeights(result);
}

/** Normalize weight per cluster supaya sum A=0.65, B=0.25, C=0.10 (target Integral). */
function normalizeClusterWeights(assignments: ClusterAssignment[]): ClusterAssignment[] {
  const targetPerCluster: Record<Cluster, number> = { A: 0.65, B: 0.25, C: 0.10 };
  const sumPerCluster: Record<Cluster, number> = { A: 0, B: 0, C: 0 };
  for (const a of assignments) sumPerCluster[a.cluster] += a.weight;
  return assignments.map((a) => {
    const sum = sumPerCluster[a.cluster];
    if (sum === 0) return a;
    const normalized = (a.weight / sum) * targetPerCluster[a.cluster];
    return { ...a, weight: Math.round(normalized * 1000) / 1000 };
  });
}

// ============================================================
// Threshold per cluster (berbasis Integral spec)
// ============================================================

export type ClusterThresholds = {
  /** Threshold "siap" / pass per cluster. */
  A: number;
  B: number;
  C: number;
};

export const DEFAULT_CLUSTER_THRESHOLDS: ClusterThresholds = {
  A: 0.80, // Direct prereq — ≥80% pass
  B: 0.85, // Supporting — ≥85% pass
  C: 0.95, // Foundation — ≥95% pass (default; di-override adaptive per jenjang user)
};

/** Build threshold cluster yang adaptive C per jenjang user. */
export function buildAdaptiveThresholds(
  targetJenjang: "SD" | "SMP" | "SMA",
  targetKelas?: number,
  base: ClusterThresholds = DEFAULT_CLUSTER_THRESHOLDS,
): ClusterThresholds {
  const target = pickFoundationTarget(targetJenjang, targetKelas);
  return { ...base, C: FOUNDATION_THRESHOLD_BY_TARGET[target] };
}

/**
 * Klasifikasi status cluster berdasarkan accuracy + threshold.
 *
 * Returns:
 *   - "siap"     : accuracy ≥ threshold cluster
 *   - "review"   : accuracy 80-94% dari threshold (mendekati tapi belum)
 *   - "remediasi": accuracy < 80% dari threshold (jauh)
 */
export function classifyClusterStatus(
  accuracy: number,
  cluster: Cluster,
  thresholds: ClusterThresholds = DEFAULT_CLUSTER_THRESHOLDS,
): "siap" | "review" | "remediasi" {
  const t = thresholds[cluster];
  if (accuracy >= t) return "siap";
  if (accuracy >= t * 0.8) return "review";
  return "remediasi";
}

// ============================================================
// Path routing 4-tier (dari Integral Table 5)
// ============================================================

export type PathRoute = {
  path: "ADVANCED" | "STANDARD" | "COMPREHENSIVE" | "INTENSIVE";
  /** Estimasi durasi tes drilling lanjutan (menit). */
  duration: string;
  fokus: string;
};

export function routePath(
  scoreA: number,
  scoreB: number,
  scoreC: number,
  thresholds: ClusterThresholds = DEFAULT_CLUSTER_THRESHOLDS,
): PathRoute {
  const A_ok = scoreA >= thresholds.A;
  const B_ok = scoreB >= thresholds.B;
  const C_ok = scoreC >= thresholds.C;

  // ADVANCED — semua mastery
  if (A_ok && B_ok && C_ok) {
    return { path: "ADVANCED", duration: "45-60 menit", fokus: "Polish & Strategy lanjutan" };
  }

  // INTENSIVE — kritis di banyak cluster
  const A_critical = scoreA < 0.6;
  const B_critical = scoreB < 0.6;
  const C_critical = scoreC < 0.85;
  const criticalCount = [A_critical, B_critical, C_critical].filter(Boolean).length;
  if (criticalCount >= 2) {
    return { path: "INTENSIVE", duration: "85-120 menit", fokus: "Emergency intervention — rebuild foundation" };
  }

  // COMPREHENSIVE — major gaps
  const A_major = scoreA < 0.7;
  const B_major = scoreB < 0.7;
  const C_major = scoreC < 0.85;
  const majorCount = [A_major, B_major, C_major].filter(Boolean).length;
  if (majorCount >= 2 || A_critical || B_critical) {
    return { path: "COMPREHENSIVE", duration: "70-95 menit", fokus: "Systematic rebuilding multi-cluster" };
  }

  // STANDARD — moderate gaps
  return { path: "STANDARD", duration: "55-75 menit", fokus: "Targeted gap filling" };
}
